<?php

declare(strict_types=1);

namespace AsceticSoft\Waypoint\Cache;

/**
 * Contract for the compiled route matcher generated by {@see RouteCompiler}.
 *
 * This interface covers only matching-related methods. Route data access and
 * name lookup are segregated into {@see CompiledRouteProviderInterface} and
 * {@see RouteNameLookupInterface} respectively.
 *
 * The generated class implements all three interfaces, stored as immutable
 * class constants in opcache shared memory.
 */
interface CompiledMatcherInterface extends CompiledRouteProviderInterface, RouteNameLookupInterface
{
    /**
     * Match a static route — O(1) hash table lookup via match expression.
     *
     * @return array{0: int, 1: array<string, string>}|null Route index and params, or null.
     */
    public function matchStatic(string $method, string $uri): ?array;

    /**
     * Get allowed HTTP methods for a static URI (for 405 responses).
     *
     * @return list<string>
     */
    public function staticMethods(string $uri): array;

    /**
     * Check if a URI can ONLY be matched via the static route table.
     *
     * Returns true when no parameterised trie route and no fallback route
     * can match this URI.  This enables an early 405 response without
     * traversing the dynamic trie or scanning fallback routes.
     */
    public function isStaticOnly(string $uri): bool;

    /**
     * Match a dynamic route — segment-by-segment trie dispatch.
     *
     * @param array<string, true> &$allowedMethods Collected allowed methods (for 405).
     *
     * @return array{0: int, 1: array<string, string>}|null Route index and params, or null.
     */
    public function matchDynamic(string $method, string $uri, array &$allowedMethods = []): ?array;
}
