<?php

declare(strict_types=1);

namespace AsceticSoft\Waypoint\Cache;

/**
 * Contract for the compiled route matcher generated by {@see RouteCompiler}.
 *
 * The generated named class implements this interface and uses PHP `match`
 * expressions (compiled to hash-table lookups by opcache) for O(1) static route
 * matching and efficient trie-based dynamic route dispatch.  Route data is
 * stored as immutable class constants, cached in opcache shared memory.
 */
interface CompiledMatcherInterface
{
    /**
     * Match a static route — O(1) hash table lookup via match expression.
     *
     * @return array{0: int, 1: array<string, string>}|null Route index and params, or null.
     */
    public function matchStatic(string $method, string $uri): ?array;

    /**
     * Get allowed HTTP methods for a static URI (for 405 responses).
     *
     * @return list<string>
     */
    public function staticMethods(string $uri): array;

    /**
     * Check if a URI can ONLY be matched via the static route table.
     *
     * Returns true when no parameterised trie route and no fallback route
     * can match this URI.  This enables an early 405 response without
     * traversing the dynamic trie or scanning fallback routes.
     */
    public function isStaticOnly(string $uri): bool;

    /**
     * Match a dynamic route — segment-by-segment trie dispatch.
     *
     * @param array<string, true> &$allowedMethods Collected allowed methods (for 405).
     *
     * @return array{0: int, 1: array<string, string>}|null Route index and params, or null.
     */
    public function matchDynamic(string $method, string $uri, array &$allowedMethods = []): ?array;

    /**
     * Get compact route data by index.
     *
     * @return array{h: array{0:class-string,1:string}|\Closure, M: list<string>, p: string, w?: list<string>, n?: string, P?: int, r?: string, N?: list<string>, a?: list<array<string, mixed>>|null}
     */
    public function getRoute(int $idx): array;

    /**
     * Total number of compiled routes.
     */
    public function getRouteCount(): int;

    /**
     * Indices of non-trie-compatible (fallback) routes.
     *
     * @return list<int>
     */
    public function getFallbackIndices(): array;

    /**
     * Find a route index by name — O(1) lookup via match expression.
     *
     * @return int|null Route index, or null if not found.
     */
    public function findByName(string $name): ?int;
}
